---
# tasks file for roles/ceph-rbd
- name: Set OSD pool default size
  ini_file: dest=/home/{{ceph_user}}/{{ceph_cluster}}/ceph.conf section=global option="osd pool default size" value="3" mode=0600 backup=no
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True

- name: Set OSD pool min size
  ini_file: dest=/home/{{ceph_user}}/{{ceph_cluster}}/ceph.conf section=global option="osd pool default min size" value="1" mode=0600 backup=no
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True

- name: Set number of placement groups
  ini_file: dest=/home/{{ceph_user}}/{{ceph_cluster}}/ceph.conf section=global option="osd pool default pg num" value="100" mode=0600 backup=no
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True

# ceph osd dump | grep 'replicated size'

- name: Create storage pools
  shell: ceph osd pool create {{ceph_storage_pool}} {{ceph_pg_num}}
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True

- name: Install ceph-client on admin
  shell: ceph-deploy install ceph-client chdir=/home/{{ceph_user}}/{{ceph_cluster}}
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True

- name: Deploy ceph-client on nodes
  shell: ceph-deploy admin ceph-client chdir=/home/{{ceph_user}}/{{ceph_cluster}}
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
