---
# This playbook deploys a Ceph cluster.
# RUN: ansible-playbook -i hosts ceph.yml

- name: open up ports
  hosts: nodes
  sudo: true
  roles:
    - { role: firewalld, tags: ["misc"] }

- name: install ceph (preflight check)
  hosts: ceph_base
  remote_user: vagrant
  sudo: true
  roles:
    - { role: ceph-preflight, tags: ["ceph"] }

- name: setup ceph admin
  hosts: ceph_admin
  remote_user: vagrant
  sudo: false
  roles:
    - { role: ceph-admin, ceph_install_mode: "base_setup", tags: ["ceph-admin"] }

- name: copy public key to nodes and add ceph to sudoers
  hosts: ceph_base
  roles:
    - { role: ceph-node }

- name: create cluster
  hosts: ceph_admin
  remote_user: ceph
  sudo: true
  roles:
    - { role: ceph-admin, ceph_install_mode: "create_cluster", tags: ["ceph-create-cluster"] }
