---
# This playbook deploys a Ceph cluster.
# RUN: ansible-playbook -i hosts ceph.yml

- name: install ceph (preflight check)
  hosts: ceph_admin
  remote_user: vagrant
  sudo: true
  roles:
    - { role: jenkins-master, jenkins_install_mode: "datas", tags: ["jenkins"] }