---
# This playbook deploys a Ceph cluster.
# RUN: ansible-playbook -i hosts ceph.yml

- name: install jenkins
  hosts: jenkins_master_outside_mesos
  roles:
    - { role: jenkins-master, tags: ["jenkins"] }