---
# tasks file for roles/ceph-admin

- name: Create ssh key if not exist
  sudo: True
  user: name={{ceph_user}} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  when: ceph_install_mode == "base_setup"

- name: Get back the key (private and public) to host
  fetch: src=/home/{{ceph_user}}/.ssh/{{ item }} dest=keys/{{ceph_user}}-{{ ansible_hostname }}-{{ item }} flat=yes
  sudo: True
  with_items:
    - id_rsa
    - id_rsa.pub
  when: ceph_install_mode == "base_setup"

- name: Setup ssh configuration of the admin node to access ceph nodes
  template: src=./ssh_config.j2 dest=/home/{{ceph_user}}/.ssh/config
  remote_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "base_setup"

- name: Give the right permissions to the ssh config
  file: name=/home/{{ceph_user}}/.ssh/config mode=0440 state=file owner={{ceph_user}}
  sudo: True
  when: ceph_install_mode == "base_setup"

- name: Add public key to ceph nodes and users
  authorized_key: user={{ ceph_user }} key="{{ lookup('file', 'keys/'+ ceph_user + '-' + ceph_admin_node + '-id_rsa.pub') }}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Establish first ssh connection as the ceph user
  shell: ssh -o StrictHostKeyChecking=no {{ceph_user}}@{{item}} "echo pong" >> first_conn.txt
  remote_user: "{{ceph_user}}"
  sudo: True
  sudo_user: "{{ceph_user}}"
  when: ceph_install_mode == "create_cluster"
  with_items:
    - node1
    - node2
    - node3
    - dk1

- name: Purge nodes to test that the connectivity is ok
  shell: ceph-deploy purgedata {{ceph_nodes}}
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Remove existing keys
  shell: ceph-deploy forgetkeys
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Create the ceph cluster configuration folder
  file: name=/home/{{ceph_user}}/{{ceph_cluster}} state=directory
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Create the cluster
  shell: ceph-deploy new {{ceph_nodes}} chdir=/home/{{ceph_user}}/{{ceph_cluster}}
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Configure replication factor
  ini_file: dest=/home/{{ceph_user}}/{{ceph_cluster}}/ceph.conf section=global option="osd pool default size" value=2 mode=0600 backup=yes
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Configure network
  ini_file: dest=/home/{{ceph_user}}/{{ceph_cluster}}/ceph.conf section=global option="public network" value={{ceph_public_ip}} mode=0600 backup=yes
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"

- name: Install the cluster
  shell: ceph-deploy install {{ceph_nodes}} {{ceph_admin_node}} chdir=/home/{{ceph_user}}/{{ceph_cluster}}
  remote_user: "{{ceph_user}}"
  sudo_user: "{{ceph_user}}"
  sudo: True
  when: ceph_install_mode == "create_cluster"
