---
# tasks file for roles/ceph-node
- name: Add public key to ceph nodes and users
  hosts: ceph
  authorized_key: user={{ ceph_user }} key="{{ lookup('file', 'keys/ceph-' + ceph_admin_node + '-id_rsa.pub') }}"
