---
# tasks file for roles/docker-registry
- name: install python setuptools
  sudo: yes
  yum: pkg=python-setuptools,python-pip state=latest

- name: install docker-py
  sudo: yes
  pip: name=docker-py

- name: images-container
  docker:
    name: private_registry
    image: registry:2.0
    state: started
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - docker-registry:/opt/docker-registry:rw

#    env:
#        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY = /opt/docker-registry
#    
#sudo docker run -d --volume-driver rbd -v registry:/var/lib/registry -p 5000:5000 --restart=always --name registry registry:2
#telnet dk1 5000
