---
# tasks file for roles/docker-registry
- name: install python setuptools
  sudo: yes
  yum: pkg=python-setuptools,python-pip,git state=latest

- name: remove old source folder
  file: name=/home/{{ansible_ssh_user}}/docker-py state=absent

- name: install docker-py dev version with volume-driver test patch - checkout
  git: repo=https://github.com/rastaman/docker-py.git dest=docker-py
# use refspec tu pull all pull requests: refspec=+refs/pull/*:refs/heads/*

- name: install docker-py dev version - build
  shell: python setup.py install chdir=/home/{{ansible_ssh_user}}/docker-py
  sudo: True

- name: images-container
  sudo: yes
  docker:
    name: private_registry
    image: registry:2.0
    state: started
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - docker-registry:/opt/docker-registry:rw
    volume_driver: rbd
    env:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY = /opt/docker-registry
#    
#sudo docker run -d --volume-driver rbd -v registry:/var/lib/registry -p 5000:5000 --restart=always --name registry registry:2
#telnet dk1 5000
