---
# tasks file for role/base
- name: update the hosts file
  template: src=./hosts.j2 dest=/etc/hosts

- name: remove fastestmirror plugin
  file: path=/etc/yum/pluginconf.d/fastestmirror.conf state=absent

- name: update centos base repo to be more predictive by the proxy
  template: src=./CentOS-Base.j2 dest=/etc/yum.repos.d/CentOS-Base.repo

- name: update yum configuration to use the proxy
  template: src=./yum.j2 dest=/etc/yum.conf
  when: install_mode == "setup_yum"

- name: install EPEL repo
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
  when: install_mode == "setup_yum"

- name: Install gcc, kernel libs and bzip2
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - kernel-devel
    - bzip2
  when: install_mode == "setup_yum"

- name: Update yum
  yum: name='*' state=latest
  when: install_mode == "setup_yum"
