---
# tasks file for role/squid

# For vagrant box:
- name: upload squid RPMS
  copy: src=squid-3.3.8-12.el7_0.x86_64.rpm dest=/tmp/squid-3.3.8-12.el7_0.x86_64.rpm

- name: install squid
  yum: name=/tmp/squid-3.3.8-12.el7_0.x86_64.rpm state=present

- name: give ownership of cache folder to squid
  file: path=/var/spool/squid group=squid owner=squid
  sudo: yes

- name: setup base configuration for squid
  copy: src=./squid.conf dest=/etc/squid/squid.conf group=root owner=root
  sudo: yes

- name: start squid
  service: name=squid state=started enabled=yes
  sudo: yes
